version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: jupyter-notebook
    ports:
      - "9988:9988"
    volumes:
      - ./notebooks:/home/jovyan/work  
    depends_on:
      - redis
